server:
  http2:
    enabled: true
spring:
  cloud:
    gateway:
  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        # 暴露的端点
        include: shutdown
  endpoint:
    #开启shutdown
    shutdown:
      enabled: true